package com.smartlearnly.backend.common.audit;

public enum AuditAction {
    ACCOUNT_REGISTERED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    LOGIN_BLOCKED,
    GOOGLE_LOGIN_SUCCEEDED,
    LOGOUT_SUCCEEDED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED,
    EMAIL_VERIFIED,
    PROFILE_UPDATED,

    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,

    COURSE_CREATED,
    COURSE_UPDATED,
    COURSE_PUBLISHED,
    COURSE_DEACTIVATED,
    COURSE_DELETED,
    COURSE_ACCESS_BLOCKED,
    COURSE_ACCESS_UNBLOCKED,

    SECTION_CREATED,
    SECTION_UPDATED,
    SECTION_DELETED,
    SECTIONS_REORDERED,

    LESSON_CREATED,
    LESSON_UPDATED,
    LESSON_DEACTIVATED,
    LESSON_DELETED,
    LESSONS_REORDERED,

    CLASS_CREATED,
    CLASS_UPDATED,
    CLASS_CANCELLED,
    CLASS_DELETED,

    ENROLLMENT_CREATED,
    ENROLLMENT_REACTIVATED,
    ENROLLMENT_STATUS_CHANGED,

    ORDER_CREATED,
    ORDER_CANCELLED,
    PAYMENT_CREATED,
    PAYMENT_CALLBACK_RECEIVED,
    PAYMENT_SUCCEEDED,
    PAYMENT_MISMATCHED,
    PAYMENT_FAILED,
    PAYMENT_RECONCILED,

    QUESTION_BANK_CREATED,
    QUESTION_BANK_UPDATED,
    QUESTION_BANK_ARCHIVED,
    QUESTION_BANK_RESTORED
}
